name = "InferenceObjects"
uuid = "b5cf5a8d-e756-4ee3-b014-01d49d192c00"
authors = ["Seth Axen <seth.axen@gmail.com> and contributors"]
version = "0.3.5"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Compat = "3.46.0, 4.2.0"
DimensionalData = "0.24"
OffsetArrays = "1"
OrderedCollections = "1"
Tables = "1"
julia = "1.6"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OffsetArrays", "OrderedCollections"]
